all:
	gcc -Wall -c doubleLinkedList.c
	gcc -Wall doubleLinkedList.o validation.c -o validation
	./validation
compile:
	gcc -Wall -c doubleLinkedList.c
	gcc -Wall doubleLinkedList.o validation.c -o validation
run:
	./validation

